# Generated by Django 2.1.5 on 2019-02-08 14:36

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título (opcional)')),
            ],
            options={
                'verbose_name_plural': 'Albuns',
            },
        ),
        migrations.CreateModel(
            name='Apoiador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.CharField(blank=True, max_length=2, null=True)),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
                ('nome', models.CharField(max_length=100)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Apoiadores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Colunista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem')),
                ('nome', models.CharField(max_length=100)),
                ('profissao', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('telefone', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Colunistas',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagem')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Album')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(default='', max_length=500)),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação')),
                ('destaque', models.BooleanField(default=False)),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem')),
                ('more_photos', models.BooleanField(default=False, verbose_name='Mais fotos ?')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noticias.Album')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='noticias.Colunista')),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='noticias.Categoria')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('link', models.URLField()),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação')),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='noticias.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Vídeos',
            },
        ),
    ]
