# Generated by Django 2.1.5 on 2019-01-20 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Publicacao',
        ),
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
    ]
