# Generated by Django 2.1.5 on 2019-01-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20190120_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='destaque',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
