# Generated by Django 2.1.5 on 2019-02-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_publicacao_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='more_photos',
        ),
        migrations.RemoveField(
            model_name='publicacao',
            name='photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='noticias.Album'),
        ),
    ]
