# Generated by Django 2.1.5 on 2019-02-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20190209_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='autor',
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='noticias.Album'),
        ),
    ]
