# Generated by Django 2.1.5 on 2019-01-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20190120_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
    ]
