# Generated by Django 2.1.5 on 2019-01-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20190120_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
