# Generated by Django 2.1.5 on 2019-06-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_video_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='video_post',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
