# Generated by Django 2.1.5 on 2019-01-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colunista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='colunistas/fotos'),
        ),
    ]
