# Generated by Django 2.1.5 on 2019-01-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_auto_20190121_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/imagens'),
        ),
    ]
