# Generated by Django 2.1.5 on 2019-01-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_auto_20190129_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='colunista',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
