# Generated by Django 2.1.5 on 2019-02-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_colunista_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='resumo',
            field=models.TextField(default='', max_length=50),
        ),
    ]
