# Generated by Django 2.1.5 on 2019-02-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_publicacao_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoiador',
            name='ordem',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
