# Generated by Django 2.1.5 on 2019-02-04 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0012_apoiador_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação'),
        ),
    ]
