# Generated by Django 2.1.5 on 2019-02-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0013_auto_20190204_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
