# Generated by Django 2.1.5 on 2019-02-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0015_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Vídeos'},
        ),
        migrations.AddField(
            model_name='video',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
