# Generated by Django 2.1.5 on 2019-02-05 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0016_auto_20190204_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação'),
        ),
    ]
