# Generated by Django 2.1.5 on 2019-02-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0017_video_data_publicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
    ]
