# Generated by Django 2.1.5 on 2019-02-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0019_video_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='categoria',
        ),
    ]
